### ISSUE TITLE
There was a problem with svwar.py

### ISSUE THREAD

**Issue by Lyttoni** [EnableSecurity/sipvicious#36]
The range specified by option -e can not be completely tested.
Example：
`python2 .\svwar.py 209.160.xx.xx -e 100-999 --force`
When the fuzz the 15 to stop.
`ERROR:TakeASip:Response: 'SIP/2.0 403 Forbidden\r\nVia: SIP/2.0/UDP 192.168.12.193:5060;branch=z9hG4bK-2904524794;received=192.168.12.193;rport=5060\r\nFrom: "15"<sip:15@209.160.xx.xx>;tag=313501333336333334353431\r\nTo: "15"<sip:15@209.160.xx.xx>\r\nCall-ID: 3309078876\r\nCSeq: 1 REGISTER\r\nServer: VOS3000 V2.1.2.6\r\nContent-Length: 0\r\n\r\n'
WARNING:root:found nothing
`
Is my method wrong?

By Google Translate... Hope you can understand

**Comment by sandrogauci** [comment]
This behavior aims to avoid flooding servers when extension enumeration appears to be not possible, as is the case of a 403 response.
