### ISSUE TITLE
missing os and pickle

### ISSUE THREAD

**Issue by z3ro** [EnableSecurity/sipvicious#37]
hello, i noticed that the svmap file is broken when using session ,
os and pickle
not included in import ,

fix this

**Comment by sandrogauci** [comment]
@z3ro please provide further details. Can you copy and paste the following:

- the command that you're running (i.e. which args you're passing to svmap)
- the output you get, errors etc
- the output of `./svmap.py --version` and which OS and python version you're using

**Comment by z3ro** [comment]
svmap.py -s xxx  1x.x.x.x-2x.x.x.x

svmap.py v0.2.8

python2.7
