### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by 0xc0decafe** [EnableSecurity/sipvicious#39]
Hi,

I try using svmap on an IPv6 target, I know runs a SIP service, but its not detected ):

>svmap.py -p5060 2001:XXXX:XXXX::1
>WARNING:root:found nothing

vs.

>Nmap scan report for 2001:XXXX:XXXX::1
>Host is up, received user-set (0.050s latency).
>Not shown: 999 filtered ports
>Reason: 999 no-responses
>PORT     STATE SERVICE REASON         VERSION
>5060/tcp open  sip     syn-ack ttl 61 (SIP end point; Status: 400 Bad magic cookie in Via-branch)

best

/daniel

**Comment by sandrogauci** [comment]
oh yes ipv6 :-/

**Comment by sandrogauci** [comment]
check the ipv6-support test branch

**Comment by 0xc0decafe** [comment]
tested with svcrack and svwar. Works for me.

thanks!

**Comment by elyasrz** [comment]
Hello sandro gauci how using scan ipv6 can give me example command for start scan and using svmap and etc
