### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by sbrun** [EnableSecurity/sipvicious#42]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).
Kali is tracking Debian Testing and is thus affected by this. You should consider to switch sipvicious to Python 3.

FWIW this is tracked in https://gitlab.com/kalilinux/packages/sipvicious/issues/1 on the Kali side.

**Comment by sandrogauci** [comment]
hey @sbrun - thanks for the notice! Will port to python 3 (leaving issue open until then)

**Comment by sandrogauci** [comment]
this is closed with PR #45
