### ISSUE TITLE
please cut a proper release

### ISSUE THREAD

**Issue by blshkv** [EnableSecurity/sipvicious#46]
so that all distros could update it. Thanks.

**Comment by sandrogauci** [comment]
more testing to be done before release. You're welcome to contribute :-)

**Comment by blshkv** [comment]
Thanks, but I don't have time to contribute. We are cleaning up hundreds of packages in Pentoo and sipvicious is one of problematic software

**Comment by sandrogauci** [comment]
we're working on that

**Comment by sandrogauci** [comment]
@blshkv made a release at https://github.com/EnableSecurity/sipvicious/releases/tag/v0.3.0
