### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by SHAW900** [EnableSecurity/sipvicious#49]
Hi 
i am not good in linux or cmd base but i try my best to run this but now i am getting this error below can you please help me and let me know where i am not doing correct:

thank you 

user@DESKTOP-BR3HB9S:~/sipvicious-0.3.0/sipvicious$ ls
__init__.py  libs  svcrack.py  svcrash.py  svmap.py  svreport.py  svwar.py
user@DESKTOP-BR3HB9S:~/sipvicious-0.3.0/sipvicious$ ./svmap.py
Traceback (most recent call last):
  **File "./svmap.py", line 36, in <module>
    from .libs.pptable import to_string
ModuleNotFoundError: No module named '__main__.libs'; '__main__' is not a package**

**Comment by 0xInfection** [comment]
Hi @SHAW900, 

Did you install the package provided properly? To install, run the command `python3 setup.py install`. After which you can use any of the tools by specifying the name `sipvicious_svmap --help`.

**Comment by sandrogauci** [comment]
closing this issue due to lack of response. Re-open if you run into this problem again

**Comment by markwhite005** [comment]
when try to install giving this
`root@ron:~/sipvicious# python setup.py install
  File "setup.py", line 54
    download_url=f'https://github.com/EnableSecurity/sipvicious/archive/v{__version__}.zip',
                                                                                          ^
SyntaxError: invalid syntax`

**Comment by 0xInfection** [comment]
@markwhite005 please use Python 3, Python 2 is deprecated.

**Comment by markwhite005** [comment]
i did and it works fine now..tell me how to scan using tcp port
