### ISSUE TITLE
 ModuleNotFoundError

### ISSUE THREAD

**Issue by yasiryassi** [EnableSecurity/sipvicious#50]
Traceback (most recent call last):
  File "./svmap.py", line 36, in <module>
    from .libs.pptable import to_string
ModuleNotFoundError: No module named '__main__.libs'; '__main__' is not a package

I am dealing with this issue in the upgraded program.

**Comment by sandrogauci** [comment]
please install the tool by using pip .. e.g. `pip install sipvicious`. That should resolve your issues

**Comment by yasiryassi** [comment]
i did it but on ubuntu 18. its not working tkxx for reply

**Comment by yasiryassi** [comment]
can you plzz tele me about sipvicious  pro
