### ISSUE TITLE
Big Problem Please Help

### ISSUE THREAD

**Issue by elyasrz** [EnableSecurity/sipvicious#51]
Hello Sir 
Sorry for the inconvenience but I have a question about sipvicious IPv6 can you please add a function to can using scan ipv6 please give me any example
I'm trying this command like sipvicious_svcrack 2406:840::/3 
or sipvicious_svmap 2406:840::/32
i got always  this message WARNING:root:found nothing

**Comment by sandrogauci** [comment]
svmap does not support IPv6 scanning. The address space for IPv6 is considerably more extensive than with IPv4, so what you're trying to do is not going to be effective, even if we supported IPv6 in svmap.

To use svwar or svcrack with IPv6 support, you need to use the `-6` flag.

**Comment by elyasrz** [comment]
thank you very much give me example command please like sipvicious_svcrack 2406:840::/3

**Comment by 0xInfection** [comment]
svmap now supports IPv6, so yea gonna mark this as resolved.
