### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mar-i0** [EnableSecurity/sipvicious#62]
# python setup.py install
  File "setup.py", line 54
    download_url=f'https://github.com/EnableSecurity/sipvicious/archive/v{__version__}.zip',
                                                                                          ^
SyntaxError: invalid syntax

**Comment by 0xInfection** [comment]
PR #58 introduced this incompatibility issue. SIPVicious breaks with Python2. It is recommended that everyone should use Python3 as Python2 has been discontinued. Nevertheless this issue will be fixed in an upcoming PR.

**Comment by markwhite005** [comment]
i used python3 and didn't work
