### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by MasterBruter** [EnableSecurity/sipvicious#63]
No matter how i install, either from pip or github whatever i do it will not run.
Tried windows and linux.

```
Traceback (most recent call last):
  File "svmap.py", line 37, in <module>
    from .libs.pptable import to_string
ImportError: attempted relative import with no known parent package
```

**Comment by 0xInfection** [comment]
Please provide more information on what platform/system as well as Python version you are on to help us assist you on this error.
> __NOTE:__ If you are trying to install sipvicious using Python2, it won't work, please use Python3.

**Comment by 0xInfection** [comment]
Closing this until further information is provided. Feel free to reopen this issue with more info.

**Comment by 3isenHeiM** [comment]
I have the exact same issue.

Platform : Ubuntu 20.04
Python : 3.8.2
Installation via git clone inside a venv
