### ISSUE TITLE
dictionary.txt

### ISSUE THREAD

**Issue by gbiagomba** [EnableSecurity/sipvicious#65]
Hello,

This is more of a request but in the example you provide you mentioned taking in a dictionary, now before i just fed in any dictionary i was wondering if you could share a sample of what that dictionary would look like? like is it alphanumeric characters? alpha only? numeric only? 

Any details you can provide would be greatly appreciated!

**Comment by sandrogauci** [comment]
hi @gbiagomba, we just updated the Wiki to give examples and link to the SecLists repository for actual dictionary files.

The following pages were updated:

- [Svwar documentation](https://github.com/EnableSecurity/sipvicious/wiki/SVWar-Usage#dictionary-guessing-mode)
- [Svcrack documentation](https://github.com/EnableSecurity/sipvicious/wiki/SVCrack-Usage#dictionary-guessing-mode)

Could you tell me if it is any clearer?

**Comment by gbiagomba** [comment]
ma man! @sandrogauci thank you!
