### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [EnableSecurity/sipvicious#68]
Hello sir how to use fingerprint she is disabled    how to make it enable i run this command 
| Fingerprint |
| disabled    |

python3 svmap.py -fp 192.168.1.1
python3 svmap.py --fp 192.168.1.1
but not working command error 

svmap.py: error: no such option: -f

thank you

**Comment by sandrogauci** [comment]
hi @VoipSip the fingerprinting functionality never worked too well even if it seemed like a great idea when I first implemented it. We had removed this actually back in 2012 :) Sorry about the misleading UI!
