### ISSUE TITLE
Man pages installing into wrong location

### ISSUE THREAD

**Issue by jkroonza** [EnableSecurity/sipvicious#77]
sipvicious setup.py by default install man pages into /usr/man/man1, where hier(7) states that /usr/man has been replaced with /usr/share/man ... as such, setup.py should be adjusted to install man pages there instead.

**Comment by sandrogauci** [comment]
hi @jkroonza, I can see this being a problem indeed. I had a tough time reproducing this issue originally, hence the delay. Do you have a fix to address this? My experiments were not very successful somehow

**Comment by jkroonza** [comment]
```sed -re 's:man/man1:share/man/man1:' -i setup.py```

During src_prepare phase of the Gentoo ebuild.   Very unsure if there is a better way.  But this managed to pass QA checks on Gentoo ... other distributions may again want other locations ... and I don't see a way to pass that as a variable of sorts to setup.py either ... (note:  what I know of python in general is dangerous - meaning more than enough to be useful, but not enough to not shoot myself in the foot every now and again)

**Comment by sandrogauci** [comment]
figured out what I was doing wrong when trying to reproduce the issue. (using `setup.py` directly instead of pip). Thanks for this!
